[package]
license = ["Apache-2.0"]
keywords = ["Human Resources/HRMS", "Cost/Freemium"]
org = "ballerinax"
name = "brex.team"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
