[package]
org = "ballerinax"
name = "interzoid.zipinfo"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
license = ["Apache-2.0"]
keywords = ["IT Operations/Cloud Services", "Cost/Freemium"]
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
