[package]
license = ["Apache-2.0"]
keywords = ["Finance/Accounting", "Cost/Paid"]
org = "ballerinax"
name = "freshbooks"
icon = "icon.png"
distribution="slbeta3"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
