[package]
org = "ballerinax"
name = "nytimes.moviereviews"
version = "0.1.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["NYTimes","Movie","Reviews","media","open_data"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
