[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Marketing Automation", "Cost/Freemium"]
org = "ballerinax"
name = "sendgrid"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.2.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
