[package]
org = "ballerinax"
name = "sendgrid"
version = "0.1.0"
authors = ["Ballerina"]
license= ["Apache-2.0"]
keywords = ["sendgrid", "send mail", "sendgrid alerts"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true