[package]
org = "ballerinax"
name = "earthref.fiesta"
version = "1.0.0-SNAPSHOT"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
authors = ["Ballerina"]
license = ["Apache-2.0"]
keywords = ["IT Operations/Geographic Information Systems", "Cost/Free"]

[build-options]
observabilityIncluded = true
