[package]
org = "ballerinax"
name = "earthref.fiesta"
version = "0.1.0-SNAPSHOT"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
authors = ["Ballerina"]
license = ["Apache-2.0"]
keywords = ["earthref", "fiesta", "opendata", "geoscience"]

[build-options]
observabilityIncluded = true
