[package]
license = ["Apache-2.0"]
keywords = ["interzoid currency conversion", "money", "freemium"]
org = "ballerinax"
name = "interzoid.convertcurrency"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
