[package]
license = ["Apache-2.0"]
keywords = ["iptwist", "geolocation", "ip"]
org = "ballerinax"
name = "iptwist"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
 
[build-options]
observabilityIncluded = true