[package]
license = ["Apache-2.0"]
keywords = ["namsor", "languages", "names", "origin"]
org = "ballerinax"
name = "namsor"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
