[package]
org = "ballerinax"
name = "fungenerators.uuid"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
license = ["Apache-2.0"]
keywords = ["fungenerators", "uuid", "random"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
