[package]
distribution = "slbeta6"
org = "ballerinax"
name = "zuora.revenue"
version = "1.1.0"
icon = "icon.png"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Finance/Accounting","Cost/Paid"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors" 
