[package]
org = "ballerinax"
name = "constantcontact"
version = "1.0.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Marketing/Marketing Automation", "Cost/Paid"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
