[package]
org = "ballerinax"
name = "interzoid.globaltime"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
license = ["Apache-2.0"]
keywords = ["interzoid", "freemium"]
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
