[package]
license = ["Apache-2.0"]
keywords = ["google", "clouddatastore", "datastore", "database", "nosql"]
org = "ballerinax"
name = "googleapis.clouddatastore"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
