[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Video & Audio", "Cost/Free"]
org = "ballerinax"
name = "themoviedb"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
