[package]
license = ["Apache-2.0"]
keywords = ["the movie database", "tmdb", "movies", "tv shows", "free"]
org = "ballerinax"
name = "themoviedb"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
