[package]
license = ["Apache-2.0"]
keywords = ["Lifestyle & Entertainment/News & Lifestyle", "Cost/Free"]
org = "ballerinax"
name = "covid19"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.7.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
