[package]
org = "ballerinax"
name = "covid19"
version = "0.4.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["covid19", "covid19 vaccine"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
