[package]
license = ["Apache-2.0"]
keywords = ["Sales & CRM", "Customer Relationship Management"]
org = "ballerinax"
name = "sugarcrm"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
