[package]
license = ["Apache-2.0"]
keywords = ["Finance/Task Management", "Cost/Freemium"]
org = "ballerinax"
name = "formstack"
icon = "icon.png"
distribution = "2201.0.2"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
