[package]

license = ["Apache-2.0"]
keywords = ["AI/OpenAI", "Cost/Paid", "GPT-3.5", "ChatGPT"]
org = "ballerinax"
name = "azure.openai.chat"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]
 
[build-options]
observabilityIncluded = true
