[package]
org = "ballerinax"
name = "googleapis.bigquery.datatransfer"
version = "0.1.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["google","bigquery", "data-transfer"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
