[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Testing Tools", "Cost/Paid"]
org = "ballerinax"
name = "optimizely"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0-SNAPSHOT"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
