[package]
license = ["Apache-2.0"]
keywords = ["Sales & CRM/Scheduling & Booking", "Cost/Freemium"]
org = "ballerinax"
name = "amadeus.flightofferssearch"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
