[package]
org = "ballerinax"
name = "godaddy.abuse"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
license = ["Apache-2.0"]
keywords = ["godaddy", "domain", "abuse", "report"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
