[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Source Control", "Cost/Freemium"]
org = "ballerinax"
name = "bitbucket"
version = "1.0.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
