[package]
license = ["Apache-2.0"]
keywords = ["stripe", "online payment processing"]
org = "ballerinax"
name = "stripe"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
