[package]
distribution = "slbeta6"
org = "ballerinax"
name = "supportbee"
icon = "icon.png"
version = "1.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Support/Customer Support","Cost/Paid"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
