[package]
org = "ballerinax"
name = "graphhopper.directions"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
license = ["Apache-2.0"]
keywords = ["graphhopper", "directions", "route", "optimization"]

[build-options]
observabilityIncluded = true