[package]
org = "ballerinax"
name = "graphhopper.directions"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0-SNAPSHOT"
authors = ["Ballerina"]
license = ["Apache-2.0"]
keywords = ["IT Operations/Cloud Services", "Cost/Freemium"]

[build-options]
observabilityIncluded = true
