[package]
distribution = "slbeta6"
license = ["Apache-2.0"]
keywords = ["Education/Dictionary", "Cost/Freemium"]
org = "ballerinax"
name = "wordnik"
icon = "icon.png"
version = "1.1.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
