[package]
license = ["Apache-2.0"]
keywords = ["Education/Dictionary", "Cost/Freemium"]
org = "ballerinax"
name = "wordnik"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
