[package]
license = ["Apache-2.0"]
keywords = ["Finance/Accounting", "Cost/Paid"]
org = "ballerinax"
name = "quickbooks.online"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.3"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
