[package]
org = "ballerinax"
name = "siemens.platformcore.identitymanagement"
version = "1.0.0-SNAPSHOT"
distribution = "slbeta3"
license = ["Apache-2.0"]
keywords = ["IT Operations/Security & Identity Tools" "Cost/Freemium"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
