[package]
org = "ballerinax"
name = "googleapis.tasks"
version = "1.0.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Productivity/Task Management", "Cost/Free", "Vendor/Google"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
