[package]
license = ["Apache-2.0"]
keywords = ["Communication/Video Conferencing", "Cost/Freemium"]
org = "ballerinax"
name = "livestorm"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "2.4.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
