[package]
org = "ballerinax"
name = "worldbank"
version = "0.1.1"
authors = ["Ballerina"]
license= ["Apache-2.0"]
keywords = ["world bank", "world bank indicators"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true