[package]
license = ["Apache-2.0"]
keywords = ["Productivity/Project Management", "Cost/Paid"]
org = "ballerinax"
name = "xero.projects"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
