[package]
distribution = "slbeta6"
license = ["Apache-2.0"]
keywords = ["Productivity/Project Management", "Cost/Paid"]
org = "ballerinax"
name = "xero.projects"
icon = "icon.png"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
