[package]
org = "ballerinax"
name = "logoraisr"
version = "0.1.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Content & Files/Images And Design", "Cost/Paid"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
