[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Images & Design", "Cost/Paid"]
org = "ballerinax"
name = "logoraisr"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.4.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
