[package]
distribution = "slbeta6"
license = ["Apache-2.0"]
keywords = ["Productivity/Project Management", "Cost/Freemium"]
org = "ballerinax"
name = "launchdarkly"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]
 
[build-options]
observabilityIncluded = true
