[package]
distribution = "slbeta6"
license = ["Apache-2.0"]
keywords = ["IT Operations/Cloud Services", "Cost/Paid", "Vendor/Microsoft"]
org = "ballerinax"
name = "azure.textanalytics"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
