[package]
distribution = "slbeta6"
license = ["Apache-2.0"]
keywords = ["Website & App Building/Website Builders", "Cost/Freemium"]
org = "ballerinax"
name = "wordpress"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.1.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
