[package]
distribution = "slbeta6"
license = ["Apache-2.0"]
keywords = ["Content & Files/File Management & Storage", "Cost/Freemium"]
org = "ballerinax"
name = "hubspot.files"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
