[package]
org = "ballerinax"
name = "googleapis.cloudtalentsolution"
version = "0.1.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Human Resources/Talent Acquisition", "Cost/Free", "Vendor/Google"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
