[package]
distribution = "slbeta6"
org = "ballerinax"
name = "paypal.payments"
icon = "icon.png"
version = "1.1.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Finance/Payment","Cost/Freemium"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
